highlighter: rouge
markdown: kramdown
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true

url: http://josephwhitman.com
baseurl: ""
title: Joseph Whitman
author: Joseph Whitman
description: Personal webpage and CV
avatar: profile.jpg
email: jwhitman89@ufl.edu
github: josephwhitman
twitter: joseph_whitman
linkedin: josephwhitman
stackoverflow: users/6789909/joe
#disqus: username
google_analytics: UA-46287878-1
