# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://josephwhitman.com
baseurl: ""
title: Joseph Whitman
author: Joseph Whitman
description: Personal webpage and CV
avatar: profile.png
email: mail@josephwhitman.com
github: josephwhitman # username
twitter: joseph_whitman
linkedin: josephwhitman
stackoverflow: users/6789909/joe
#disqus: username
#google_analytics: 


# needed for travis-ci build
# exclude: [vendor]
